blank_issues_enabled: false
contact_links:

  - name: cntact me via email
    url: mailto:lolmc2022@outlook.com
    about: If the issue is extremely gamebreaking, please contact me here, as this will send a message straight to my phone. **PLEASE DO NOT ABUSE, OR YOU WILL BE BLACKLISTED FROM MY EMAIL**
  - name: Bowmand117
    url: https://scratch.mit.edu/users/bowmand117
    about: My account on scratch.

  - name: Scratch Community
    url: https://scratch.mit.edu/studios/31997852/
    about: The main studio where everything made by the community goes. If you have any questios, people will most likely be able to answer here, although it may take some time.

  - name: topPVZmaster
    url: https://scratch.mit.edu/users/topPVZmaster
    about: The Founder of the collaboration studio. He will most likely have answers to any questions you have regarding lore, plans, and more.
  - name: topPVBmaster
    url: https://scratch.mit.edu/users/topPVBmaster
    about: The Co-Founder of the collab. He will also likely have answers about questions reguarding lore and so on.
